//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace core.audiamus.connect.ui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("core.audiamus.connect.ui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adult product.
        /// </summary>
        internal static string AdultProduct {
            get {
                return ResourceManager.GetString("AdultProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Australia.
        /// </summary>
        internal static string au {
            get {
                return ResourceManager.GetString("au", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average rating.
        /// </summary>
        internal static string AverageRating {
            get {
                return ResourceManager.GetString("AverageRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bit rate.
        /// </summary>
        internal static string BitRate {
            get {
                return ResourceManager.GetString("BitRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book.
        /// </summary>
        internal static string Book {
            get {
                return ResourceManager.GetString("Book", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Books.
        /// </summary>
        internal static string Books {
            get {
                return ResourceManager.GetString("Books", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book series.
        /// </summary>
        internal static string bookseries {
            get {
                return ResourceManager.GetString("bookseries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canada.
        /// </summary>
        internal static string ca {
            get {
                return ResourceManager.GetString("ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to conversion error.
        /// </summary>
        internal static string conversion_error {
            get {
                return ResourceManager.GetString("conversion_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to converted, not found.
        /// </summary>
        internal static string converted_unknown {
            get {
                return ResourceManager.GetString("converted_unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deregister devive.
        /// </summary>
        internal static string CptDeregisterDevice {
            get {
                return ResourceManager.GetString("CptDeregisterDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existing profiles.
        /// </summary>
        internal static string CptExistingProfiles {
            get {
                return ResourceManager.GetString("CptExistingProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Profile.
        /// </summary>
        internal static string CptRemProfile {
            get {
                return ResourceManager.GetString("CptRemProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Germany.
        /// </summary>
        internal static string de {
            get {
                return ResourceManager.GetString("de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery type.
        /// </summary>
        internal static string DeliveryType {
            get {
                return ResourceManager.GetString("DeliveryType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to download error.
        /// </summary>
        internal static string download_error {
            get {
                return ResourceManager.GetString("download_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spain.
        /// </summary>
        internal static string es {
            get {
                return ResourceManager.GetString("es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File size.
        /// </summary>
        internal static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to France.
        /// </summary>
        internal static string fr {
            get {
                return ResourceManager.GetString("fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgBlank {
            get {
                object obj = ResourceManager.GetObject("ImgBlank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgCheck {
            get {
                object obj = ResourceManager.GetObject("ImgCheck", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgCheckGrey {
            get {
                object obj = ResourceManager.GetObject("ImgCheckGrey", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgCheckMauve {
            get {
                object obj = ResourceManager.GetObject("ImgCheckMauve", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgDown {
            get {
                object obj = ResourceManager.GetObject("ImgDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgDownBroken {
            get {
                object obj = ResourceManager.GetObject("ImgDownBroken", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgGlobe {
            get {
                object obj = ResourceManager.GetObject("ImgGlobe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgGlobeDown {
            get {
                object obj = ResourceManager.GetObject("ImgGlobeDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgKey {
            get {
                object obj = ResourceManager.GetObject("ImgKey", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgKeyDenied {
            get {
                object obj = ResourceManager.GetObject("ImgKeyDenied", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgLocked {
            get {
                object obj = ResourceManager.GetObject("ImgLocked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgPlus {
            get {
                object obj = ResourceManager.GetObject("ImgPlus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgQuestion {
            get {
                object obj = ResourceManager.GetObject("ImgQuestion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgRedX {
            get {
                object obj = ResourceManager.GetObject("ImgRedX", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgRight {
            get {
                object obj = ResourceManager.GetObject("ImgRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgRightFailed {
            get {
                object obj = ResourceManager.GetObject("ImgRightFailed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgUnlocked {
            get {
                object obj = ResourceManager.GetObject("ImgUnlocked", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgUnlocking {
            get {
                object obj = ResourceManager.GetObject("ImgUnlocking", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ImgUnlockingFailed {
            get {
                object obj = ResourceManager.GetObject("ImgUnlockingFailed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to India.
        /// </summary>
        internal static string in_ {
            get {
                return ResourceManager.GetString("in_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italy.
        /// </summary>
        internal static string it {
            get {
                return ResourceManager.GetString("it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japan.
        /// </summary>
        internal static string jp {
            get {
                return ResourceManager.GetString("jp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Library.
        /// </summary>
        internal static string Library {
            get {
                return ResourceManager.GetString("Library", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License denied.
        /// </summary>
        internal static string license_denied {
            get {
                return ResourceManager.GetString("license_denied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License obtained.
        /// </summary>
        internal static string license_granted {
            get {
                return ResourceManager.GetString("license_granted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local, locked.
        /// </summary>
        internal static string local_locked {
            get {
                return ResourceManager.GetString("local_locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to local, unlocked.
        /// </summary>
        internal static string local_unlocked {
            get {
                return ResourceManager.GetString("local_unlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deregister device &quot;{0}&quot;
        ///for region/domain &quot;{1}&quot; 
        ///and account &quot;{2}&quot;?
        ///
        ///The corresponding profile has been overwritten.
        ///The device can also be deregistered via Amazon account management..
        /// </summary>
        internal static string MsgDeregisterDevice {
            get {
                return ResourceManager.GetString("MsgDeregisterDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A previous profile exists for region/domain &quot;{0}&quot;
        ///and account &quot;{1}&quot;.
        ///Signing in with the same account will overwrite that profile..
        /// </summary>
        internal static string MsgExistingAccount {
            get {
                return ResourceManager.GetString("MsgExistingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous profiles exist for region/domain &quot;{0}&quot;
        ///and accounts &quot;{1}&quot;.
        ///Signing in with one of the same accounts will overwrite that profile..
        /// </summary>
        internal static string MsgExistingAccounts {
            get {
                return ResourceManager.GetString("MsgExistingAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization failed.
        ///Please try again..
        /// </summary>
        internal static string MsgNewProfileAuthorizationFailed {
            get {
                return ResourceManager.GetString("MsgNewProfileAuthorizationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New profile created.
        ///Region / domain: &quot;{0}&quot;
        ///Account: &quot;{1}&quot;
        ///Device: &quot;{2}&quot;
        ///
        ///Previous deviice &quot;{3}&quot;
        ///should be deregistered via Amazon account management..
        /// </summary>
        internal static string MsgNewProfileDeregistrationFailed {
            get {
                return ResourceManager.GetString("MsgNewProfileDeregistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New profile created.
        ///Region / domain: &quot;{0}&quot;
        ///Account: &quot;{1}&quot;
        ///Device: &quot;{2}&quot;
        ///
        ///Warning: Deregistration failed for previous device: 
        ///&quot;{3}&quot;
        ///The device can still be deregistered via Amazon account management..
        /// </summary>
        internal static string MsgNewProfileDeregistrationFailedOrig {
            get {
                return ResourceManager.GetString("MsgNewProfileDeregistrationFailedOrig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL.
        ///Please try again..
        /// </summary>
        internal static string MsgNewProfileInvalidUrl {
            get {
                return ResourceManager.GetString("MsgNewProfileInvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device registration failed..
        /// </summary>
        internal static string MsgNewProfileRegistrationFailed {
            get {
                return ResourceManager.GetString("MsgNewProfileRegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success. New profile created.
        ///Region / domain: &quot;{0}&quot;
        ///Account: {1}
        ///Device: &quot;{2}&quot;.
        /// </summary>
        internal static string MsgNewProfileSucc {
            get {
                return ResourceManager.GetString("MsgNewProfileSucc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove profile failed..
        /// </summary>
        internal static string MsgRemProfileError {
            get {
                return ResourceManager.GetString("MsgRemProfileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile removed.
        ///
        ///Associated device &quot;{0}&quot;
        ///should be deregistered via Amazon account management..
        /// </summary>
        internal static string MsgRemProfileOk {
            get {
                return ResourceManager.GetString("MsgRemProfileOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile removed and device deregistered..
        /// </summary>
        internal static string MsgRemProfileOkOrig {
            get {
                return ResourceManager.GetString("MsgRemProfileOkOrig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove profile for
        ///region/domain &quot;{0}&quot;, 
        ///account &quot;{1}&quot;?
        ///
        ///Associated device: &quot;{2}&quot;
        ///should be deregistered via Amazon account management..
        /// </summary>
        internal static string MsgRemProfileQuestion {
            get {
                return ResourceManager.GetString("MsgRemProfileQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove profile for
        ///region/domain &quot;{0}&quot;, 
        ///account &quot;{1}&quot;?
        ///
        ///Associated device: &quot;{2}&quot;
        ///will be deregistered as well..
        /// </summary>
        internal static string MsgRemProfileQuestionOrig {
            get {
                return ResourceManager.GetString("MsgRemProfileQuestionOrig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile removed, 
        ///but device &quot;{0}&quot;
        ///could not be deregistered.
        ///
        ///The device can also be deregistered via Amazon account management..
        /// </summary>
        internal static string MsgRemProfileWarn {
            get {
                return ResourceManager.GetString("MsgRemProfileWarn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi part book.
        /// </summary>
        internal static string multipartbook {
            get {
                return ResourceManager.GetString("multipartbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Part.
        /// </summary>
        internal static string Part {
            get {
                return ResourceManager.GetString("Part", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parts.
        /// </summary>
        internal static string Parts {
            get {
                return ResourceManager.GetString("Parts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase date.
        /// </summary>
        internal static string PurchaseDate {
            get {
                return ResourceManager.GetString("PurchaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Release date.
        /// </summary>
        internal static string ReleaseDate {
            get {
                return ResourceManager.GetString("ReleaseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not downloaded.
        /// </summary>
        internal static string remote {
            get {
                return ResourceManager.GetString("remote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample rate.
        /// </summary>
        internal static string SampleRate {
            get {
                return ResourceManager.GetString("SampleRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single part book.
        /// </summary>
        internal static string singlepartbook {
            get {
                return ResourceManager.GetString("singlepartbook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United Kingdom.
        /// </summary>
        internal static string uk {
            get {
                return ResourceManager.GetString("uk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unlocking.
        /// </summary>
        internal static string unlocking {
            get {
                return ResourceManager.GetString("unlocking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unlocking error.
        /// </summary>
        internal static string unlockingFailed {
            get {
                return ResourceManager.GetString("unlockingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to United States.
        /// </summary>
        internal static string us {
            get {
                return ResourceManager.GetString("us", resourceCulture);
            }
        }
    }
}
