//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace core.audiamus.connect.app.gui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("core.audiamus.connect.app.gui.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Audio48 {
            get {
                object obj = ResourceManager.GetObject("Audio48", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder for .
        /// </summary>
        internal static string CptSelectFolder {
            get {
                return ResourceManager.GetString("CptSelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Wizard.
        /// </summary>
        internal static string CptWizard {
            get {
                return ResourceManager.GetString("CptWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download cover images ....
        /// </summary>
        internal static string MsgDnldCoverImg {
            get {
                return ResourceManager.GetString("MsgDnldCoverImg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialiizing database ....
        /// </summary>
        internal static string MsgInitDB {
            get {
                return ResourceManager.GetString("MsgInitDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialiizing library ....
        /// </summary>
        internal static string MsgInitLib {
            get {
                return ResourceManager.GetString("MsgInitLib", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version {0}{1} of {2} is available.{3}
        ///Download now?.
        /// </summary>
        internal static string MsgOnlineUpdateDownload {
            get {
                return ResourceManager.GetString("MsgOnlineUpdateDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version {0}{1} of {2} is ready for installation.
        ///Install now?.
        /// </summary>
        internal static string MsgOnlineUpdateInstallLater {
            get {
                return ResourceManager.GetString("MsgOnlineUpdateInstallLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New version {0}{1} of {2} is ready for installation.
        ///Install now? (Will close current {2} window.).
        /// </summary>
        internal static string MsgOnlineUpdateInstallNow {
            get {
                return ResourceManager.GetString("MsgOnlineUpdateInstallNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string MsgOnlineUpdatePreview {
            get {
                return ResourceManager.GetString("MsgOnlineUpdatePreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initial setup aborted.
        ///
        ///Make the remaining settings via the main window..
        /// </summary>
        internal static string MsgWzardWarning {
            get {
                return ResourceManager.GetString("MsgWzardWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string SysMenuItemAbout {
            get {
                return ResourceManager.GetString("SysMenuItemAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string SysMenuItemHelp {
            get {
                return ResourceManager.GetString("SysMenuItemHelp", resourceCulture);
            }
        }
    }
}
